import Head from 'next/head';
import { Layout } from 'antd/lib';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import style from './container.module.scss';

const { Header, Footer, Content } = Layout;

export default
function Container(props: { children?: React.ReactNode }) {
  return <Layout className={style.container}>
    <Head>
      <title>RainbowKit App</title>
      <meta
        content="Generated by @rainbow-me/create-rainbowkit"
        name="description"
      />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <Header className={style.header}>
      <span></span>
      <ConnectButton />
    </Header>
    <Content className={style.content}>
      {props.children}
    </Content>
    <Footer className={style.footer}>Footer</Footer>
  </Layout>;
}
