import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, Space } from 'antd';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <Space>
          <Button type="primary">你好，世界</Button>
          <ConnectButton />
        </Space>
      </main>

      <footer>
      </footer>
    </div>
  );
};

export default Home;
