import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, Input, Space } from 'antd';
import { Sender } from './Sender';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <div style={{ width: '480px', padding: '20px' }}>
          <Sender />
        </div>
      </main>

      <footer>
      </footer>
    </div>
  );
};

export default Home;
